export interface ComEventDTO {
    _id: string;
    _declaration: Declaration;
    OrderList?: (OrderListEntity)[] | null;
  }
  export interface Declaration {
    _attributes: Attributes;
  }
  export interface Attributes {
    version: string;
    encoding: string;
  }
  export interface OrderListEntity {
    Order?: (OrderEntity)[] | null;
    InboxList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDCustNotificationInfoList?: (HDCustNotificationInfoListEntity)[] | null;
  }
  export interface OrderEntity {
    _attributes: Attributes1;
    Extn?: (ExtnEntity)[] | null;
    OrderHoldTypes?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    OrderLineRelationships?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    Awards?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    Promotions?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    OrderLines?: (OrderLinesEntity)[] | null;
    PersonInfoBillTo?: (PersonInfoBillToEntity)[] | null;
    PersonInfoShipTo?: (PersonInfoShipToEntity)[] | null;
    PaymentMethods?: (PaymentMethodsEntity)[] | null;
    ChargeTransactionDetails?: (ChargeTransactionDetailsEntity)[] | null;
    Notes?: (NotesEntity)[] | null;
    ProductServiceAssocs?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    AdditionalAddresses?: (AdditionalAddressesEntity)[] | null;
    Instructions?: (InstructionsEntity)[] | null;
    OverallTotals?: (OverallTotalsEntity)[] | null;
  }
  export interface Attributes1 {
    Createuserid: string;
    DocumentType: string;
    DraftOrderFlag: string;
    EnterpriseCode: string;
    EntryType: string;
    Lockid: string;
    MaxOrderStatus: string;
    MaxOrderStatusDesc: string;
    MessageId?: string | null;
    MinOrderStatus: string;
    MinOrderStatusDesc: string;
    Modifyts: string;
    OrderDate: string;
    OrderHeaderKey: string;
    OrderNo: string;
    OrderType: string;
    OriginalTotalAmount: string;
    SearchCriteria2: string;
    SellerOrganizationCode: string;
    TaxExemptionCertificate: string;
    BuyerOrganizationCode?: string | null;
  }
  export interface ExtnEntity {
    _attributes: Attributes2;
    HDOnlineHeaderList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDOrderStatusList?: (HDOrderStatusListEntity)[] | null;
    HDOrdAppParmTypeList?: (HDOrdAppParmTypeListEntity)[] | null;
    HDPaymentStageInfoList?: (HDPaymentStageInfoListEntity)[] | null;
    HDOrdChangeList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDOrdChangeDescList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDChargeTxnAdditionalList?: (HDChargeTxnAdditionalListEntity)[] | null;
    HDSplOrdList?: (HDSplOrdListEntity)[] | null;
    HDCustDsgnCustOrdList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDWillCallList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDInvoiceList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    ExtnHDStorePaymentInfoList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDPaymentMethodAddlList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDStorePaymentInfoList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
  }
  export interface Attributes2 {
    ExtnClientExternalOrderReference?: string | null;
    ExtnClientExternalSrcProcess?: string | null;
    ExtnClientExternalSrcReference?: string | null;
    ExtnCreateUserID?: string | null;
    ExtnCustGoldenRecID?: string | null;
    ExtnDepositAmount?: string | null;
    ExtnHCustomerID?: string | null;
    ExtnHostOrderReference: string;
    ExtnHostSrcProcess?: string | null;
    ExtnLCustomerID?: string | null;
    ExtnLegacyHostSrcProcess?: string | null;
    ExtnLegacyOrderReference?: string | null;
    ExtnModifiedUserID?: string | null;
    ExtnOrderLevelExtendedTotal?: string | null;
    ExtnOrderType?: string | null;
    ExtnPMCFlag: string;
    ExtnPOCreateDate: string;
    ExtnPriceProgramTier?: string | null;
    ExtnProfileID?: string | null;
    ExtnRefundRering?: string | null;
    ExtnRevisedUserID?: string | null;
    ExtnSVSOrderStatus: string;
    ExtnSVSOrderStatusDesc: string;
    ExtnSVSOrderVersion?: string | null;
    ExtnSVSPublishTimeStamp?: string | null;
    ExtnSalesTaxRate?: string | null;
    ExtnSrcRef?: string | null;
    ExtnStatusEffectiveTs: string;
    ExtnTaxExemptTypeCode?: string | null;
    ExtnUCMID?: string | null;
    ExtnUserDeptNbr?: string | null;
    ExtnMVendorNo?: string | null;
    ExtnPONumber?: string | null;
    ExtnSuppressTransmissionFlag?: string | null;
    ExtnTransmissionMechCode?: string | null;
    ExtnTransmissionStatusCode?: string | null;
    ExtnTransmissionTypeCode?: string | null;
    ExtnVendorName?: string | null;
  }
  export interface HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity {
    HDOnlineProduct;
    HDTrackingInfo;
  }
  export interface HDOrderStatusListEntity {
    HDOrderStatus?: (HDOrderStatusEntity)[] | null;
  }
  export interface HDOrderStatusEntity {
    _attributes: Attributes3;
  }
  export interface Attributes3 {
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    HDOrderStatusKey: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderHeaderKey: string;
    OrigSrcModifyID?: string | null;
    SrcModifyID: string;
    StatusCode: string;
    StatusDescription: string;
    StatusEffectiveTs: string;
    StoreNumber: string;
    UserAuditID: string;
    isHistory: string;
  }
  export interface HDOrdAppParmTypeListEntity {
    HDOrdAppParmType?: (HDOrdAppParmTypeEntity)[] | null;
  }
  export interface HDOrdAppParmTypeEntity {
    _attributes: Attributes4;
  }
  export interface Attributes4 {
    Code: string;
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    HDOrdAppParmTypeKey: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderHeaderKey: string;
    TimeStamp: string;
    UserID: string;
    Value: string;
    isHistory: string;
  }
  export interface HDPaymentStageInfoListEntity {
    HDPaymentStageInfo?: (HDPaymentStageInfoEntity)[] | null;
  }
  export interface HDPaymentStageInfoEntity {
    _attributes: Attributes5;
  }
  export interface Attributes5 {
    CountryCode: string;
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    HDPaymentStageInfoKey: string;
    HostOrderLineReference: string;
    LineNumber: string;
    LineType: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderHeaderKey: string;
    POSTransID: string;
    PostalCode: string;
    Quantity: string;
    RefundQuantity: string;
    Status: string;
    SuspendFlag: string;
    TaxCity: string;
    TaxCounty: string;
    TaxFlag: string;
    TaxRate: string;
    TaxState: string;
    TimeStamp: string;
    UnitNetRetail: string;
    isHistory: string;
  }
  export interface HDChargeTxnAdditionalListEntity {
    HDChargeTxnAdditional?: (HDChargeTxnAdditionalEntity)[] | null;
  }
  export interface HDChargeTxnAdditionalEntity {
    _attributes: Attributes6;
  }
  export interface Attributes6 {
    CollectionDate: string;
    ConcatenatedEJKey: string;
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    DepositCollectedAmount: string;
    EJDate: string;
    EJRegister: string;
    EJSeqNo: string;
    EJStore: string;
    HDChargeTxnAdditionalKey: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderHeaderKey: string;
    POSTransID: string;
    PaymentCreateTs: string;
    PaymentIdentifier: string;
    PaymentSeqNo: string;
    isHistory: string;
  }
  export interface HDSplOrdListEntity {
    HDSplOrd?: (HDSplOrdEntity)[] | null;
  }
  export interface HDSplOrdEntity {
    _attributes: Attributes7;
  }
  export interface Attributes7 {
    AllowCoupon: string;
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    HDSplOrdKey: string;
    HostOrderReference: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderHeaderKey: string;
    SoCreateTs: string;
    SplOrdAutoFaxNotifyDate: string;
    SplOrdCordSrcProsCd: string;
    SplOrdCordSrcRef: string;
    SplOrdDeliveryAgentNumber: string;
    SplOrdDeliveryLocIndicator: string;
    SplOrdExpectedArrivalDate: string;
    SplOrdIsDirectShip: string;
    SplOrdLineNumber: string;
    SplOrdModifyCordSrcRef: string;
    SplOrdQuoteLeadTime: string;
    SplOrdVendorOrderedDate: string;
    SplOrderRelatedNumber: string;
    isHistory: string;
  }
  export interface OrderLinesEntity {
    OrderLine?: (OrderLineEntity)[] | null;
  }
  export interface OrderLineEntity {
    _attributes: Attributes8;
    Extn?: (ExtnEntity1)[] | null;
    Item?: (ItemEntity)[] | null;
    LinePriceInfo?: (LinePriceInfoEntity)[] | null;
    OrderHoldTypes?: (OrderHoldTypesEntity)[] | null;
    OrderLineReservations?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    OrderDates?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    PersonInfoShipTo?: (PersonInfoShipToEntity1)[] | null;
    ChildOrderLineRelationships?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    ParentOrderLineRelationships?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    AdditionalAddresses?: (AdditionalAddressesEntity)[] | null;
    WorkOrders?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    Instructions?: (InstructionsEntity1)[] | null;
    ItemDetails?: (ItemDetailsEntity)[] | null;
    ServiceAssociations?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    ProductAssociations?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    Schedules?: (SchedulesEntity)[] | null;
    LineOverallTotals?: (LineOverallTotalsEntity)[] | null;
    LineCharges?: (LineChargesEntity)[] | null;
    LineTaxes?: (LineTaxesEntity)[] | null;
    OrderStatuses?: (OrderStatusesEntity)[] | null;
    OrderLineTranQuantity?: (OrderLineTranQuantityEntity)[] | null;
  }
  export interface Attributes8 {
    CarrierServiceCode: string;
    ConditionVariable1: string;
    CustomerLinePONo: string;
    CustomerPONo: string;
    DeliveryMethod: string;
    FulfillmentType: string;
    IsFirmPredefinedNode: string;
    ItemGroupCode: string;
    KitCode: string;
    LineType: string;
    MaxLineStatus: string;
    MaxLineStatusDesc: string;
    MinLineStatus: string;
    MinLineStatusDesc: string;
    OrderLineKey: string;
    OrderedQty: number;
    OriginalOrderedQty: string;
    PrimeLineNo: string;
    ReturnReason: string;
    SCAC: string;
    ScacAndService: string;
    ShipNode: string;
    ShipToKey: string;
    Status: string;
    StatusQuantity: string;
    SubLineNo: string;
    DerivedFromOrderLineKey?: string | null;
    ReqShipDate?: string | null;
  }
  export interface ExtnEntity1 {
    _attributes: Attributes9;
    HDOrderlineAddnlList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDOnlineProductList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDInstallAddnlInfoList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDSplOrderInfoList?: (HDSplOrderInfoListEntity)[] | null;
    HDOnlineReturnInfoList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDOrderLineAppParmTypeList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDSurveyList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDCostAuditList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDLineTaxList?: (HDLineTaxListEntity)[] | null;
    HDRelatedEJKeysList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDReturnPolicyList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDLineChgHistList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDTrackingInfoList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
    HDEventList?: (HDEventListEntity)[] | null;
    HDAppliedTransactionList?: (HDAppliedTransactionListEntity)[] | null;
    HDLineStatusList?: (HDLineStatusListEntity)[] | null;
  }
  export interface Attributes9 {
    ExtnCancelQuantity?: string | null;
    ExtnCancelReasonCode?: string | null;
    ExtnClass?: string | null;
    ExtnCreateSrcProcess?: string | null;
    ExtnCreateSrcReference?: string | null;
    ExtnCreatets: string;
    ExtnCumPickedQuantity: string;
    ExtnDFCSourceFlag?: string | null;
    ExtnDeliveryApprover: string;
    ExtnDeliveryPalletQty: string;
    ExtnDepartmentCode: string;
    ExtnFILineType?: string | null;
    ExtnHDUOMCode: string;
    ExtnHDUOMCodeDesc: string;
    ExtnHazmatCode?: string | null;
    ExtnHostOrderLineReference: string;
    ExtnHostUserID?: string | null;
    ExtnInventoryTrackCode?: string | null;
    ExtnIsPreBOSS?: string | null;
    ExtnLastNotifySent: string;
    ExtnLineLevelExtendedTotal?: string | null;
    ExtnMVendorNo: string;
    ExtnMilitaryFlag: string;
    ExtnModifySrcProcess?: string | null;
    ExtnModifySrcReference?: string | null;
    ExtnMsgGeneratedTS: string;
    ExtnNMMultilineFlag: string;
    ExtnNetUnitPrice?: string | null;
    ExtnNetUnitPriceNoTax?: string | null;
    ExtnOrderCreateLocation?: string | null;
    ExtnOrderCreateLocationType?: string | null;
    ExtnOrderLineType?: string | null;
    ExtnOriginalQtyOnQuote: string;
    ExtnPOCreateDate: string;
    ExtnPONumber?: string | null;
    ExtnPickCompleted?: string | null;
    ExtnPickedQuantity?: string | null;
    ExtnProductTypeCode?: string | null;
    ExtnProfileID?: string | null;
    ExtnRefundQuantity?: string | null;
    ExtnReleaseType?: string | null;
    ExtnReturnQuantity?: string | null;
    ExtnRoundingDeferred?: string | null;
    ExtnSKUCode: number;
    ExtnSKUCodeDesc: string;
    ExtnSellingLocation: string;
    ExtnSplOrderLineNumber: string;
    ExtnSubClass?: string | null;
    ExtnSystemReference?: string | null;
    ExtnTenderQuantity?: string | null;
    ExtnUOMConvQty?: string | null;
    ExtnUncancelledQty: string;
    ExtnVendorStockNumber: string;
    ExtnWillCallLineNum?: string | null;
    ExtnCancelReqSent?: string | null;
    ExtnPOLineReference?: string | null;
    ExtnPOTrnsMonTriggered?: string | null;
    ExtnUnitCost?: string | null;
    ExtnOMSID?: string | null;
  }
  export interface HDSplOrderInfoListEntity {
    HDSplOrderInfo?: (HDSplOrderInfoEntity)[] | null;
  }
  export interface HDSplOrderInfoEntity {
    _attributes: Attributes10;
  }
  export interface Attributes10 {
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    DeliveryTypeCode: string;
    HDSplOrderInfoKey: string;
    Lockid: string;
    ManfacMdlNumber: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderLineKey: string;
    ReturnPolicyID: string;
    isHistory: string;
  }
  export interface HDLineTaxListEntity {
    HDLineTax?: (HDLineTaxEntity)[] | null;
  }
  export interface HDLineTaxEntity {
    _attributes: Attributes11;
  }
  export interface Attributes11 {
    CreateTimeStamp: string;
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    HDLineTaxComKey: string;
    HDLineTaxKey: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderLineKey: string;
    POSTaxCode: string;
    POSTransID: string;
    Salests: string;
    Tax: string;
    TaxCalcMethod: string;
    TaxName: string;
    TaxRate: string;
    isHistory: string;
  }
  export interface HDEventListEntity {
    HDEvent?: (HDEventEntity)[] | null;
  }
  export interface HDEventEntity {
    _attributes: Attributes12;
  }
  export interface Attributes12 {
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    EventTrkCode: string;
    EventTs: string;
    EventUserAuditID: string;
    HDEventKey: string;
    Lockid: string;
    MerQty: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderLineKey: string;
    Store: string;
    isHistory: string;
    POSTransID?: string | null;
    EventRsnCode?: string | null;
  }
  export interface HDAppliedTransactionListEntity {
    HDAppliedTransaction?: (HDAppliedTransactionEntity)[] | null;
  }
  export interface HDAppliedTransactionEntity {
    _attributes: Attributes13;
  }
  export interface Attributes13 {
    CancelReasonCode: string;
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    DerivedTransactionType: string;
    HDAppliedTransactionKey: string;
    HostOrderLineReference: string;
    HostOrderReference: string;
    HostUserID: string;
    InventoryTrackCode: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderLineKey: string;
    QuantityToCancel: string;
    RefundQuantity: string;
    SVSRemEntriesReqd: string;
    SystemReference: string;
    SystemReferenceTS: string;
    TenderQuantity: string;
    isHistory: string;
  }
  export interface HDLineStatusListEntity {
    HDLineStatus?: (HDLineStatusEntity)[] | null;
  }
  export interface HDLineStatusEntity {
    _attributes: Attributes14;
  }
  export interface Attributes14 {
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    HDLineStatusKey: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    OrderLineKey: string;
    SrcModifyID: string;
    StatusCode: string;
    StatusDescription: string;
    StatusEffectiveTs: string;
    StoreNumber: string;
    UserAuditID: string;
    isHistory: string;
  }
  export interface ItemEntity {
    _attributes: Attributes15;
  }
  export interface Attributes15 {
    ItemDesc: string;
    ItemID: string;
    ItemShortDesc: string;
    ItemWeight: string;
    ItemWeightUOM: string;
    ManufacturerItem: string;
    ManufacturerName: string;
    ProductClass: string;
    UPCCode: string;
    UnitCost: string;
    UnitOfMeasure: string;
  }
  export interface LinePriceInfoEntity {
    _attributes: Attributes16;
  }
  export interface Attributes16 {
    ListPrice: string;
    PricingQtyConversionFactor: string;
    RetailPrice: string;
    TaxableFlag: string;
    UnitPrice: string;
  }
  export interface OrderHoldTypesEntity {
    OrderHoldType?: (OrderHoldTypeEntity)[] | null;
  }
  export interface OrderHoldTypeEntity {
    _attributes: Attributes17;
  }
  export interface Attributes17 {
    HoldType: string;
    LastHoldTypeDate: string;
    Modifyuserid: string;
    OrderAuditKey: string;
    OrderHeaderKey: string;
    ReasonText: string;
    Status: string;
    StatusDescription: string;
    TransactionId: string;
    TransactionName: string;
  }
  export interface PersonInfoShipToEntity1 {
    _attributes: Attributes18;
    Extn?: (ExtnEntity2)[] | null;
  }
  export interface Attributes18 {
    AddressLine1: string;
    AddressLine2: string;
    AddressLine3: string;
    AddressLine4: string;
    AddressLine5: string;
    Beeper: string;
    City: string;
    Company: string;
    Country: string;
    DayPhone: string;
    EMailID: string;
    FirstName: string;
    JobTitle: string;
    LastName: string;
    MiddleName: string;
    MobilePhone: string;
    OtherPhone: string;
    PersonID: string;
    PersonInfoKey: string;
    State: string;
    Suffix: string;
    Title: string;
    ZipCode: string;
  }
  export interface ExtnEntity2 {
    _attributes: Attributes19;
  }
  export interface Attributes19 {
    AddressType: string;
    ExtnCounty: string;
    ExtnHostOrderLineReference: string;
    ExtnMilitaryFlag: string;
    ExtnStrtName: string;
    ExtnSvsTypeCode: string;
    ExtnTaxRate: string;
    OrderHeaderKey: string;
  }
  export interface AdditionalAddressesEntity {
    _attributes: Attributes20;
  }
  export interface Attributes20 {
    NumberOfAdditionalAddresses: string;
  }
  export interface InstructionsEntity1 {
    _attributes: Attributes21;
    Instruction?: (InstructionEntity)[] | null;
  }
  export interface Attributes21 {
    NumberOfInstructions: string;
  }
  export interface InstructionEntity {
    _attributes: Attributes22;
    Extn?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
  }
  export interface Attributes22 {
    Action: string;
    Createprogid: string;
    Createts: string;
    Createuserid: string;
    InstructionDetailKey: string;
    InstructionText: string;
    InstructionType: string;
    InstructionURL: string;
    InstructionUsage: string;
    Lockid: string;
    Modifyprogid: string;
    Modifyts: string;
    Modifyuserid: string;
    ReferenceKey: string;
    SequenceNo: string;
    TableName: string;
    isHistory: string;
  }
  export interface ItemDetailsEntity {
    _attributes: Attributes23;
    PrimaryInformation?: (PrimaryInformationEntity)[] | null;
    Extn?: (ExtnEntity3)[] | null;
  }
  export interface Attributes23 {
    ItemID: string;
  }
  export interface PrimaryInformationEntity {
    _attributes: Attributes24;
  }
  export interface Attributes24 {
    IsHazmat: string;
    TaxableFlag: string;
  }
  export interface ExtnEntity3 {
    _attributes: Attributes25;
  }
  export interface Attributes25 {
    ExtnClass: string;
    ExtnDFCSourceFlag?: string | null;
    ExtnDepartment: string;
    ExtnPackageQuantity?: string | null;
    ExtnSubClass: string;
  }
  export interface SchedulesEntity {
    Schedule?: (ScheduleEntity)[] | null;
  }
  export interface ScheduleEntity {
    _attributes: Attributes26;
    ScheduleTranQuantity?: (ScheduleTranQuantityEntity)[] | null;
  }
  export interface Attributes26 {
    BatchNo: string;
    ExpectedDeliveryDate: string;
    ExpectedShipmentDate: string;
    LotNumber: string;
    OrderHeaderKey: string;
    OrderLineKey: string;
    OrderLineScheduleKey: string;
    Quantity: string;
    RevisionNo: string;
    ScheduleNo: string;
    ShipNode: string;
    TagNumber: string;
  }
  export interface ScheduleTranQuantityEntity {
    _attributes: Attributes27;
  }
  export interface Attributes27 {
    Quantity: string;
    TransactionalUOM: string;
  }
  export interface LineOverallTotalsEntity {
    _attributes: Attributes28;
  }
  export interface Attributes28 {
    Charges: string;
    Discount: string;
    ExtendedPrice: string;
    LineCost: string;
    LineTotal: string;
    LineTotalWithoutTax: string;
    ManualDiscountPercentage: string;
    OptionPrice: string;
    PercentProfitMargin: string;
    PricingQty: string;
    ShippingBaseCharge: string;
    ShippingCharges: string;
    ShippingDiscount: string;
    ShippingTotal: string;
    Tax: string;
    UnitPrice: string;
  }
  export interface LineChargesEntity {
    LineCharge?: (LineChargeEntity)[] | null;
  }
  export interface LineChargeEntity {
    _attributes: Attributes29;
    Extn?: (ExtnEntity4)[] | null;
  }
  export interface Attributes29 {
    ChargeAmount: string;
    ChargeCategory: string;
    ChargeName: string;
    ChargeNameKey: string;
    ChargePerLine: string;
    ChargePerUnit: string;
    InvoicedChargeAmount: string;
    InvoicedChargePerLine: string;
    InvoicedChargePerUnit: string;
    IsBillable: string;
    IsDiscount: string;
    Reference: string;
    RemainingChargeAmount: string;
    RemainingChargePerLine: string;
    RemainingChargePerUnit: string;
  }
  export interface ExtnEntity4 {
    _attributes: Attributes30;
  }
  export interface Attributes30 {
    ExtnApprvrUserID: string;
    ExtnComputedChargePerUnit: string;
    ExtnCouponID: string;
    ExtnCreateTimeStamp: string;
    ExtnCreateUserID: string;
    ExtnCreatets: string;
    ExtnDerivedChargePerUnitForLC: string;
    ExtnPOSStgTranID: string;
    ExtnPOSStgTranTS: string;
    ExtnPromotionID: string;
    ExtnPromotionType: string;
    ExtnQuantity: string;
    ExtnReasonCode: string;
    ExtnReasonText: string;
    ExtnSlsPromoCpntID: string;
  }
  export interface LineTaxesEntity {
    LineTax?: (LineTaxEntity)[] | null;
  }
  export interface LineTaxEntity {
    _attributes: Attributes31;
    Extn?: (ExtnEntity5)[] | null;
  }
  export interface Attributes31 {
    ChargeCategory: string;
    ChargeName: string;
    ChargeNameKey: string;
    InvoicedTax: string;
    Reference1: string;
    Reference2: string;
    Reference3: string;
    RemainingTax: string;
    Tax: string;
    TaxName: string;
    TaxPercentage: string;
    TaxableFlag: string;
  }
  export interface ExtnEntity5 {
    _attributes: Attributes32;
  }
  export interface Attributes32 {
    ExtnExtendedTaxPerLine: string;
  }
  export interface OrderStatusesEntity {
    OrderStatus?: (OrderStatusEntity)[] | null;
  }
  export interface OrderStatusEntity {
    _attributes: Attributes33;
    Details?: (DetailsEntity)[] | null;
    OrderStatusTranQuantity?: (OrderStatusTranQuantityEntity)[] | null;
  }
  export interface Attributes33 {
    OrderHeaderKey: string;
    OrderLineKey: string;
    OrderLineScheduleKey: string;
    OrderReleaseStatusKey: string;
    PipelineKey: string;
    ShipNode: string;
    Status: string;
    StatusDate: string;
    StatusDescription: string;
    StatusQty: string;
    TotalQuantity: string;
  }
  export interface DetailsEntity {
    _attributes: Attributes34;
  }
  export interface Attributes34 {
    ExpectedDeliveryDate: string;
    ExpectedShipmentDate: string;
    TagNumber: string;
  }
  export interface OrderStatusTranQuantityEntity {
    _attributes: Attributes35;
  }
  export interface Attributes35 {
    StatusQty: string;
    TotalQuantity: string;
    TransactionalUOM: string;
  }
  export interface OrderLineTranQuantityEntity {
    _attributes: Attributes36;
  }
  export interface Attributes36 {
    FillQuantity: string;
    InvoicedQuantity: string;
    OpenQty: string;
    OrderedQty: string;
    OriginalOrderedQty: string;
    ReceivedQty: string;
    RemainingQty: string;
    SettledQuantity: string;
    ShippedQuantity: string;
    SplitQty: string;
    StatusQuantity: string;
    TranDiscrepancyQty: string;
    TransactionalUOM: string;
  }
  export interface PersonInfoBillToEntity {
    _attributes: Attributes37;
    Extn?: (ExtnEntity6)[] | null;
  }
  export interface Attributes37 {
    AddressLine1: string;
    AddressLine2: string;
    AddressLine3: string;
    AddressLine4: string;
    AddressLine5: string;
    AddressLine6: string;
    AlternateEmailID: string;
    Beeper: string;
    City: string;
    Company: string;
    Country: string;
    DayFaxNo: string;
    DayPhone: string;
    Department: string;
    EMailID: string;
    EveningFaxNo: string;
    EveningPhone: string;
    FirstName: string;
    JobTitle: string;
    LastName: string;
    MiddleName: string;
    MobilePhone: string;
    OtherPhone: string;
    PersonID: string;
    PersonInfoKey: string;
    State: string;
    Suffix: string;
    Title: string;
    ZipCode: string;
    Latitude?: string | null;
    Longitude?: string | null;
  }
  export interface ExtnEntity6 {
    _attributes: Attributes38;
  }
  export interface Attributes38 {
    AddressType?: string | null;
    ExtnCounty?: string | null;
    ExtnHostOrderLineReference?: string | null;
    ExtnMilitaryFlag: string;
    OrderHeaderKey?: string | null;
  }
  export interface PersonInfoShipToEntity {
    _attributes: Attributes18;
    Extn?: (ExtnEntity7)[] | null;
  }
  export interface ExtnEntity7 {
    _attributes: Attributes39;
  }
  export interface Attributes39 {
    ExtnMilitaryFlag: string;
    AddressType?: string | null;
    ExtnCounty?: string | null;
    ExtnHostOrderLineReference?: string | null;
    ExtnStrtName?: string | null;
    ExtnSvsTypeCode?: string | null;
    ExtnTaxRate?: string | null;
    OrderHeaderKey?: string | null;
  }
  export interface PaymentMethodsEntity {
    PaymentMethod?: (PaymentMethodEntity)[] | null;
  }
  export interface PaymentMethodEntity {
    _attributes: Attributes40;
  }
  export interface Attributes40 {
    BillToKey: string;
    CheckNo: string;
    CheckReference: string;
    CreditCardExpDate: string;
    CreditCardName: string;
    CreditCardNo: string;
    CreditCardType: string;
    CustomerPONo: string;
    DisplayCreditCardNo: string;
    DisplayCustomerAccountNo: string;
    DisplayPaymentReference1: string;
    DisplaySvcNo: string;
    FundsAvailable: string;
    GetFundsAvailableUserExitInvoked: string;
    MaxChargeLimit: string;
    PaymentKey: string;
    PaymentReference1: string;
    PaymentReference2: string;
    PaymentReference3: string;
    PaymentReference9: string;
    PaymentType: string;
    TotalAuthorized: string;
    TotalCharged: string;
    TotalRefundedAmount: string;
    UnlimitedCharges: string;
  }
  export interface ChargeTransactionDetailsEntity {
    ChargeTransactionDetail?: (ChargeTransactionDetailEntity)[] | null;
  }
  export interface ChargeTransactionDetailEntity {
    _attributes: Attributes41;
    CreditCardTransactions?: (CreditCardTransactionsEntity)[] | null;
  }
  export interface Attributes41 {
    AuthorizationID: string;
    ChargeTransactionKey: string;
    ChargeType: string;
    CollectionDate: string;
    CreditAmount: string;
    OpenAuthorizedAmount: string;
    PaymentKey: string;
    RequestAmount: string;
    SettledAmount: string;
    Status: string;
  }
  export interface CreditCardTransactionsEntity {
    CreditCardTransaction?: (CreditCardTransactionEntity)[] | null;
  }
  export interface CreditCardTransactionEntity {
    _attributes: Attributes42;
  }
  export interface Attributes42 {
    AuthCode: string;
    AuthTime: string;
    DepositCollectedAmount: string;
    EJDate: string;
    EJRegister: string;
    EJSeqNo: string;
    EJStore: string;
    InvoiceNo: string;
    OrigEJDate: string;
    OrigEJRegister: string;
    OrigEJSeqNo: string;
    OrigEJStore: string;
    POSTransID: string;
    PaymentApproveUserAuditId: string;
    PaymentCreateTs: string;
    PaymentCreateUserId: string;
    PaymentReasonCode: string;
    PaymentSeqNo: string;
    PaymentUserDefReasonDesc: string;
    Reference1: string;
    TranReturnCode: string;
    TranType: string;
  }
  export interface NotesEntity {
    _attributes: Attributes43;
  }
  export interface Attributes43 {
    NumberOfNotes: string;
  }
  export interface InstructionsEntity {
    _attributes: Attributes21;
    Instruction?: (InstructionEntity1)[] | null;
  }
  export interface InstructionEntity1 {
    _attributes: Attributes22;
    Extn?: (ExtnEntity8)[] | null;
  }
  export interface ExtnEntity8 {
    _attributes?: Attributes44 | null;
  }
  export interface Attributes44 {
    ExtnCrtModID?: string | null;
    ExtnFulfillingStore?: string | null;
    ExtnIsTicklerBin: string;
    ExtnStore?: string | null;
    ExtnTimeStamp?: string | null;
    ExtnUserID?: string | null;
    ExtnCloseDate?: string | null;
    ExtnCloseUserID?: string | null;
    ExtnFollowUpDate?: string | null;
  }
  export interface OverallTotalsEntity {
    _attributes: Attributes45;
    Extn?: (ExtnEntity9)[] | null;
  }
  export interface Attributes45 {
    GrandCharges: string;
    GrandDiscount: string;
    GrandShippingBaseCharge: string;
    GrandShippingCharges: string;
    GrandShippingDiscount: string;
    GrandShippingTotal: string;
    GrandTax: string;
    GrandTotal: string;
    HdrCharges: string;
    HdrDiscount: string;
    HdrShippingBaseCharge: string;
    HdrShippingCharges: string;
    HdrShippingDiscount: string;
    HdrShippingTotal: string;
    HdrTax: string;
    HdrTotal: string;
    LineSubTotal: string;
    ManualDiscountPercentage: string;
    PercentProfitMargin: string;
  }
  export interface ExtnEntity9 {
    _attributes: Attributes46;
  }
  export interface Attributes46 {
    ExtnReturnTotal: string;
  }
  export interface HDCustNotificationInfoListEntity {
    HDCustNotificationInfo?: (HDCustNotificationInfoEntity)[] | null;
  }
  export interface HDCustNotificationInfoEntity {
    _attributes: Attributes47;
    HDNotificationEventList?: (HDOnlineHeaderListEntityOrHDOrdChangeListEntityOrHDOrdChangeDescListEntityOrHDSplOrdListEntityOrHDCustDsgnCustOrdListEntityOrHDWillCallListEntityOrHDInvoiceListEntityOrExtnHDStorePaymentInfoListEntityOrOrderHoldTypesEntityOrOrderLineRelationshipsEntityOrAwardsEntityOrPromotionsEntityOrHDOrderlineAddnlListEntityOrHDOnlineProductListEntityOrHDInstallAddnlInfoListEntityOrHDOnlineReturnInfoListEntityOrHDOrderLineAppParmTypeListEntityOrHDSurveyListEntityOrHDCostAuditListEntityOrHDRelatedEJKeysListEntityOrHDReturnPolicyListEntityOrHDLineChgHistListEntityOrHDTrackingInfoListEntityOrOrderLineReservationsEntityOrOrderDatesEntityOrChildOrderLineRelationshipsEntityOrParentOrderLineRelationshipsEntityOrWorkOrdersEntityOrServiceAssociationsEntityOrProductAssociationsEntityOrHDLineTaxListEntityOrLineChargesEntityOrProductServiceAssocsEntityOrHDOrdAppParmTypeListEntityOrHDPaymentStageInfoListEntityOrHDChargeTxnAdditionalListEntityOrHDPaymentMethodAddlListEntityOrHDStorePaymentInfoListEntityOrHDEventListEntityOrHDAppliedTransactionListEntityOrHDLineStatusListEntityOrExtnEntityOrLineTaxesEntityOrPaymentMethodsEntityOrChargeTransactionDetailsEntityOrInboxListEntityOrHDNotificationEventListEntity)[] | null;
  }
  export interface Attributes47 {
    AdhocTriggerFlag: string;
    HostOrderRef: string;
    NotificationKey: string;
    NotificationLevel: string;
    NotificationLevelRefNum: string;
    NotificationTypeCode: string;
  }
  